//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSSWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingrForRecipe
    {
        public string recipe { get; set; }
        public Nullable<int> soft_tortilla { get; set; }
        public Nullable<int> seasoned_beef { get; set; }
        public Nullable<int> cheese { get; set; }
        public Nullable<int> lettuce { get; set; }
    
        public virtual recipe recipe1 { get; set; }
    }
}
