//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSSWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class userData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userData()
        {
            this.shopStock = new HashSet<shopStock>();
        }
    
        public int id { get; set; }
        public System.DateTime creation { get; set; }
        public string username { get; set; }
        public decimal money { get; set; }
        public int employees { get; set; }
        public string shopName { get; set; }
        public string learnedRecipes { get; set; }
    
        public virtual login login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shopStock> shopStock { get; set; }
    }
}
