//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scratch
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int msg_id { get; set; }
        public int from_id { get; set; }
        public int to_id { get; set; }
        public System.DateTime time { get; set; }
        public string message { get; set; }
    
        public virtual login login { get; set; }
        public virtual login login1 { get; set; }
    }
}
