//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scratch
{
    using System;
    using System.Collections.Generic;
    
    public partial class shopStock
    {
        public int owner_id { get; set; }
        public string ingredient { get; set; }
        public int stock { get; set; }
    
        public virtual ingredients ingredients { get; set; }
        public virtual userData userData { get; set; }
    }
}
