//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace scratch
{
    using System;
    using System.Collections.Generic;
    
    public partial class userData
    {
        public string userid { get; set; }
        public int money { get; set; }
        public int employees { get; set; }
        public string username { get; set; }
    }
}
